language: ruby
rvm:
- 2.2.2
before_script:
- chmod +x ./script/deploy-gh
script: ./script/deploy-gh
branches:
  only:
  - gh-pages
env:
  global:
  - GH_USERNAME=theengineroom-engineers
  - GH_OWNER=the-engine-room
  - GH_REPO=2017-retro
  - GH_REF=github.com/the-engine-room/2017-retro.git
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: pU5wfMD3lMghoxVXduLgaB2JSNwTkkn+HEdkxImXXJUZaI+lwULnGTCrFGFy4WRbj7HtnllKQvMd3KEkiMZknThK56KLBVnXmdCltZQH5BcJHMn7mNRk+OSUSGFuIds8nbs7MOAaI+27LRDW5LMIPkkMXMTVOB56XUAUwKW12JwhTbYcgTs+P0sQE9RzUtsrGiIA3lZ5wJ0VcEWtWiG+p+d8rAHXKo7Rs1vwFXdfLbWJyVJdjTOHI2w9tKvPJhNNrn2H/5SVEK0n87ZsjaPavGu1z2fjNNnFqKaolglqjBG71RwvTn69Ebygks66all/10P0NoVyEHdAlt7vIk/rycEUy0c27NfR01Ouz1mBoywzR15QuvpQFkQ1NqCtWUT+quiLsz+9kNQhnTVX8OPeJWKdQUHzUzBCNDOnC7lUb9wYPnPrw8NB/Z8EFs3Qsp3fGJE20VtZpoiBkDH1kaLXYv5Hw+NHCNOXNQ98uJnA4kr2G5l9isr8RAjo8aqt3uBBGhfMSVyuct7VDqrTHqDfPWzjbx9GC3Rb7xo4zuVlR77kw5HmI99L44ATlCv3zPzvACxGhuIYyADcAzTGlJ5itVNrJX2GiIk4vr6+Vpe8jBLRmu5tpy436+ioiGczMpugGl6C6v++vnJEK4clPTlT8N2WCezjjg0GFLG9jsR5hPk=
sudo: false
