language: ruby
rvm:
- 2.2.2
before_script:
- chmod +x ./script/deploy-gh
script: "./script/deploy-gh"
branches:
  only:
  - gh-pages
env:
  global:
  - GH_USERNAME=theengineroom-engineers
  - GH_EMAIL=engineers@theengineroom.org
  - GH_OWNER=the-engine-room
  - GH_REPO=2017-retro
  - GH_REF=github.com/the-engine-room/2017-retro.git
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
