language: ruby
rvm:
- 2.1
before_script:
- chmod +x ./script/deploy-gh
script: "./script/deploy-gh"
branches:
  only:
  - gh-pages
env:
  global:
  - GH_USERNAME=mayarichman
  - GH_OWNER=the-engine-room
  - GH_REPO=2016-retro
  - GH_REF=github.com/the-engine-room/2016-retro.git
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - secure: aJAsBwB+Mikq2vlfNB1c5BZNi2TafAUiOexsfvjE1pvpLxOPze86SePzR4e15qWO1BNFSztiX9gbgXGJZXMfmxS+eMCLRIALxMjrvbEdzCma5BEvGZEjyfC1Y1r4alwufZ931YGvejOON0X5M8ThaOWVgb+EItDDBN0TFrsIlgEU3x++oTe7HcwSkc4J+MJ/L+/D9ColwKwlA0RDqGNBMjSLHmJEic833/IvGcgeIfihfFYwTfP+lpAiO5HKegsxHTRP6GdKrZSRBOPSu7kpmq6x8Ju5t+2BrotDbzz51Vp+6D7lHZr71AVL2Kf29um3lov/Ivki39iy5yN4sz8vJmosFMhyD+GiecSfkKMQsZ832nyErqhLZa9kIG1+6ql6acvSOMkDpLLzkBhjC89PCCUtruzuMKjfqXaXD14qfoa9JXaePk4eolEsQUuVJIvRiEJLVVSjznmMdXQnOIU3hro3S9xUKllosaJ1+n+Vckh5n5Q7CGWX1Zb0Ze8l956lfPzXQhGDtcqHnHDgwHbpzfBlSjryLQ4+NoYnqQGGXRsB0gTRmGpdlpJ48xDVW+mirf0eMHxpYQpYI0KgrvQB1DPoJieTTqs4XCZKjwWU1cs2Be206lDSNbxI2bw0fHODhm1uhL/VwlnETrYxSqftPZcLDqmw6jqntD/eHCFdvEw=
sudo: false
notifications:
  slack:
    secure: jIzZqhtQnd7m9gedYto+9vvBpSp1MO2vdHO2GnXM1WS+05mlmzFzAdMnxybDNvevdoFrienu+RmPNT1sNHckwjNA6n+jK+StrqlQgOfkToBXwuz2nE9mmzSRb2jxE31fii4yxAvob/HVUYqqTH/jjIQoYZ/HQ+inxiAV1kO048eaUsFBnC9y1/5J0voAX3ra0Uzft6IVytlD+VwzfDtyVIvozHhI1/cQzQsFjKCDK/1EZO5x6VnCJzcO+rpjqSrX9sSrZUgzkmcbSb2oH5QRlSbKgUizGvSbA69wcUjMkKOIZDOZr4PFH793DoItnZ+ca7tmQkGC2JnhNtFf+t/SckmMwTJmhE7Ihzqc0J18IREXJiywmtzCKwXoosxw2Q7uTGefDhVop2M2hAPoAsH6fSVe/AHsNMHPBx53b+p0H9ovAso5LNcp6BGN/sRTFoJlehdjzKieFTVIuJSn1R/Uo+BcGbHEgSvaNkjCosW42vUvzKdV0xLWQCOGBU1044lq9fX4AL8J8PHubSYooH/pHay0zZAqDe4/VBSWJKnlmOt9uTKENzv8B6Q11bwYWcWJcMCyr1zNNxsPLl1B4L5IYCKjbVF7RYi9trGrynQ5DulJOKsvNwS5KjHfoMdETe98qcmIT6GutoZ+gGSswuUU3xpvJbxJDBLSIkt/vLcAf/A=
