baseurl: ""

sass:
    sass_dir: _sass

exclude: [vendor]

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      body_class: "default"
      show_navbar: true
      show_footer: true
